name: Deploy MkDocs Site

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのソースコードをチェックアウトする
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Python環境をセットアップする
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. pipをアップグレードし、MkDocsとテーマをインストールする
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material markdown-katex

      # 4. サイトをビルドする
      - name: Build site
        run: mkdocs build

      # 5. ビルドしたサイトをgh-pagesブランチにデプロイする
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
